# Meta Analysis -------------------------------------------
### SECOND STAGE ###
# loading packages
library(tidyverse)
library(mgcv)
library(stats)
library(dlnm)
library(mixmeta)
library(patchwork)
library(xlsx)
options(scipen=999)
theme_set(theme_bw())
# loafing data
data <- read_rds(paste0("00.data//data_m_w.rds")) %>% 
  mutate(mun_name = mun_name %>% as.factor())
n_var <- list("all","CVD", "RD")
for(o in n_var){
  print(o)
  # loading coefs ------------------------------------------------------------
  coef_all <- read_rds(paste0("03.output//coef_",o,".rds"))
  vcov_all <- read_rds(paste0("03.output//vcov_",o,".rds"))
  # City level meta-data
  city_info <- coef_all %>% rownames() %>% tibble(mun_name = .) %>% 
    left_join(data) %>% dplyr::select(c(1,15,16)) %>% unique
  # Meta analysis -----------------------------------------------------------
  # cities as random effects
  # one level random effects (cities within a region)
  meta_model <- mixmeta(coef_all,vcov_all, random = ~1|Region/mun_name, data = city_info,
                        method="ml")
  # Saving model in environment
  assign(paste0("meta_model_",o),meta_model)
  
  # Predictions -------------------------------------------------------------
  # Base for predictions -- using same attributed of the cross-basis in estimation
  # Avg HNE distribution
  percentiles <- seq(0, 999, by = 1) / 1000
  avg_HNE = quantile(data$HNE, probs = percentiles)
  avg_HNE = tibble(percentile = percentiles, value = avg_HNE)
  # knots
  knots = avg_HNE %>%  filter(percentile %in% c(0.50,0.90))
  knots = knots$value
  # base
  x_argvar = avg_HNE$value 
  b_argvar = onebasis(x_argvar, fun = "ns",knots = knots)
  # Random-effects 
  # Overall meta-analysis
  pred_overall <- crosspred(b_argvar, 
                            coef = coef(meta_model), vcov = vcov(meta_model),cen =0,
                            model.link="log", by=0.1)
  
  ## by regions
  region_name <- c("North","Northeast","Southeast","South","Midwest")
  # Predctions generated by blups 
  blup_region <- unique(blup(meta_model, pi=T, level= 1, vcov = T))
  for (i in c(1:5)){
    # BLUPs
    blup_temp <- blup_region[[i]]
    # SEPARATED PREDICTION FOR EACH REGION
    assign(x = paste0('pred_',region_name[i]),
           crosspred(b_argvar, 
                     coef = blup_temp$blup, vcov = blup_temp$vcov,cen = 0,
                     model.link="log", by = 0.1))
  }
  # PLOTS -------------------------------------------------------------------
  print("plotting")
  #Extract values
  tib_plot <- function(pred){
    
    return(tibble(x = pred$predvar,
                  fit = pred$matRRfit, 
                  low = pred$matRRlow, 
                  high = pred$matRRhigh))
  }
  # Overall Prediction
  P0 <-  ggplot(pred_overall %>% tib_plot(),aes(x=x,y = fit))+
    geom_line(color =  'steelblue')+
    geom_ribbon(aes(ymin = low, ymax = high),fill = "steelblue", alpha = 0.2) +
    geom_hline(aes(yintercept = 1))+
    geom_vline(aes(xintercept = 37), linetype = 2, color = "steelblue")+
    xlab("HNE")+
    ylab("RR")+
    ggtitle("Overall")
  
  # Regions
  regions_pred <- list(pred_North,pred_Northeast,pred_Midwest,
                       pred_Southeast,pred_South)
  regions_names <- c("North", "Northeast","Midwest","Southeast","South")
  for (i in 1:5){
    pred <- regions_pred[[i]]
    P <-  ggplot(pred %>% tib_plot(),aes(x=x,y = fit))+
      geom_line(color =  'steelblue')+
      geom_ribbon(aes(ymin = low, ymax = high),fill = "steelblue", alpha = 0.2) +
      xlab("HNE")+
      ylab("RR")+
      geom_hline(aes(yintercept = 1))+
      geom_vline(aes(xintercept = 37), linetype = 2, color = "steelblue")+
      ggtitle(paste0(regions_names[i]))
    
    
    assign(paste0("p_",i),P)
  }
  
  e <- ifelse(o == "all","All Cause Mortality",o)
  e <- ifelse(o == "CVD","Cardiovascular Mortality",e)
  e <- ifelse(o == "RD","Respiratory Disease Mortality",e)
  # patchwork
  layout <- "
AAAABB
AAAACC
EEFFDD
"
  plot_e <- P0+ p_1+p_2+p_3+p_4+p_5 +
    plot_layout(design = layout)+
    plot_annotation(title = paste0(e))
  ggsave(paste0("02.plots//main//02.meta_analysis_",o,".tiff"),
         dpi = 600,height = 6, width = 10 )
  
  # Tables
  # RR values in different percentiles
  percentis <- avg_HNE %>% filter (percentile %in% c(0.99))
  
  regions_pred <- list(pred_North,pred_Northeast,pred_Midwest,
                       pred_Southeast,pred_South, pred_overall)
  regions_names <- c("North", "Northeast","Midwest","Southeast","South","Overall")
  pred_table <- tibble()
  for (a in 1:6){
    
    pred_table <- bind_rows(pred_table,regions_pred[[a]] %>% tib_plot() %>% 
                              filter (x %in% round(percentis$value)) %>% 
                              bind_cols(percentil  = percentis$percentile, 
                                        pred = regions_names[a]))  
    
  }
  colnames(pred_table) <- c("HNE", "fit", "low", "high", "percentil", "pred")
  # saving as object
  assign(paste0("table_",o),pred_table)
}
# uniting tables
table_all <- tibble(table_all, `Mortality Group` = "All Causes" )
table_CVD <- tibble(table_CVD, `Mortality Group` = "CVD" )
table_RD <- tibble(table_RD, `Mortality Group` = "RD" )
# merge
table_pred_complete <- bind_rows(table_all,table_CVD,table_RD)
# Removing excess of information
table_pred_complete <- table_pred_complete %>% select(-HNE)
# Creating CI variable
table_pred_complete <- table_pred_complete %>% 
mutate(CI = paste0("(", round(low, 2), " - ", round(high, 2), ")")) %>%
  select(fit, CI, pred, `Mortality Group`)
# Saving table 
write.xlsx(table_pred_complete, paste0("01.tables//main//01.table_prediction.xlsx"))
